-- Dashboard widget configuration table
-- Global table (no org_id): 5 fixed slots for the dashboard
CREATE TABLE public.dashboard_widgets (
  id bigserial PRIMARY KEY,
  slot text NOT NULL UNIQUE
    CHECK (slot IN ('kpi_1','kpi_2','kpi_3','kpi_4','chart_1')),
  widget_type text NOT NULL CHECK (widget_type IN ('kpi','chart')),

  -- Display labels
  title text NOT NULL,
  subtitle text,
  trend_label text,
  trend_description text,

  -- KPI formatting
  value_format text CHECK (value_format IN ('currency','number','percentage','integer')),
  value_prefix text,
  value_suffix text,

  -- Chart config
  chart_type text CHECK (chart_type IN ('area','bar','line')) DEFAULT 'area',
  x_axis_key text DEFAULT 'date',
  y_axis_key text DEFAULT 'value',

  -- The SQL query (generated by AI agent)
  sql_query text,

  -- AI conversation that produced the SQL (for audit/re-editing)
  conversation_history jsonb DEFAULT '[]'::jsonb,

  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  updated_by text
);

-- Seed the 5 fixed widget slots with current hardcoded titles
INSERT INTO public.dashboard_widgets (slot, widget_type, title, subtitle, trend_label, trend_description, value_format)
VALUES
  ('kpi_1', 'kpi', 'Loan Amount Funded', NULL, 'Funding volume up this month', 'Total funded over the last 6 months', 'currency'),
  ('kpi_2', 'kpi', 'New Borrowers', NULL, 'Up 8.2% this period', 'New borrower acquisition this quarter', 'integer'),
  ('kpi_3', 'kpi', 'Active Loans', NULL, 'Strong loan activity', 'Active loans across all programs', 'integer'),
  ('kpi_4', 'kpi', 'Growth Rate', NULL, 'Steady performance', 'Meets growth projections', 'percentage');

INSERT INTO public.dashboard_widgets (slot, widget_type, title, subtitle, chart_type, x_axis_key, y_axis_key)
VALUES
  ('chart_1', 'chart', 'Deals Funded', 'Deals funded over the last 30 days', 'area', 'date', 'value');

-- RLS: readable by authenticated, writable by internal admins
ALTER TABLE public.dashboard_widgets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "dashboard_widgets_select" ON public.dashboard_widgets
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "dashboard_widgets_update" ON public.dashboard_widgets
  FOR UPDATE TO authenticated
  USING (
    (SELECT is_internal_yn FROM public.organizations WHERE clerk_organization_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'org_id')) = true
    AND (current_setting('request.jwt.claims', true)::jsonb ->> 'org_role') IN ('admin', 'owner')
  );

CREATE POLICY "dashboard_widgets_insert" ON public.dashboard_widgets
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT is_internal_yn FROM public.organizations WHERE clerk_organization_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'org_id')) = true
    AND (current_setting('request.jwt.claims', true)::jsonb ->> 'org_role') IN ('admin', 'owner')
  );
