-- =====================================================
-- Migration 1: RBAC Permissions Foundation
-- Date: 2026-01-28
-- Description: Create role-based access control infrastructure
-- Dependencies: None
-- Breaking Changes: None
-- Risk Level: LOW
-- =====================================================

BEGIN;

-- =====================================================
-- Create rbac_permissions table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.rbac_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  role text NOT NULL,
  resource_type text NOT NULL,
  resource_name text NOT NULL,
  can_select boolean NULL DEFAULT false,
  can_insert boolean NULL DEFAULT false,
  can_update boolean NULL DEFAULT false,
  can_delete boolean NULL DEFAULT false,
  scope_type text NULL,
  scope_filter text NULL,
  description text NULL,
  priority integer NULL DEFAULT 100,
  is_active boolean NULL DEFAULT true,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT rbac_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT rbac_permissions_unique UNIQUE (role, resource_type, resource_name),
  CONSTRAINT rbac_permissions_resource_type_check CHECK (
    resource_type = ANY (ARRAY['table'::text, 'storage_bucket'::text, 'api_endpoint'::text])
  ),
  CONSTRAINT rbac_permissions_scope_type_check CHECK (
    scope_type = ANY (ARRAY['all'::text, 'own'::text, 'org'::text, 'deal'::text, 'custom'::text])
  )
) TABLESPACE pg_default;

-- =====================================================
-- Create indexes for performance
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_rbac_permissions_role 
  ON public.rbac_permissions USING btree (role) 
  TABLESPACE pg_default
  WHERE (is_active = true);

CREATE INDEX IF NOT EXISTS idx_rbac_permissions_resource 
  ON public.rbac_permissions USING btree (resource_type, resource_name) 
  TABLESPACE pg_default
  WHERE (is_active = true);

CREATE INDEX IF NOT EXISTS idx_rbac_permissions_lookup 
  ON public.rbac_permissions USING btree (role, resource_type, resource_name) 
  TABLESPACE pg_default
  WHERE (is_active = true);

-- =====================================================
-- Enable RLS
-- =====================================================
ALTER TABLE public.rbac_permissions ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- Create RLS policies (admin-only for now)
-- =====================================================
CREATE POLICY "Internal admins can manage permissions"
  ON public.rbac_permissions
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE clerk_user_id = auth.uid()::text 
        AND is_internal_yn = true
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE clerk_user_id = auth.uid()::text 
        AND is_internal_yn = true
    )
  );

-- =====================================================
-- Verification
-- =====================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_name = 'rbac_permissions'
  ) THEN
    RAISE EXCEPTION 'Migration 1 failed: rbac_permissions table not created';
  END IF;
  
  RAISE NOTICE 'Migration 1 completed successfully';
END $$;

COMMIT;

-- =====================================================
-- Post-migration notes:
-- - Table created with proper constraints
-- - Indexes created for query performance
-- - RLS enabled with admin-only policies
-- - Ready to populate with permission data
-- =====================================================
