-- ============================================================================
-- Migration: Sync local schema with remote dashboard changes
-- Date: 2026-02-15
-- Author: AI (tracking changes made by Chris Lesnik via Supabase dashboard)
--
-- This migration captures:
--   1. Table renames performed on the remote
--   2. 31 tables created on the remote but not tracked by local migrations
--
-- All statements are idempotent (IF NOT EXISTS / exception handling)
-- so this migration is safe on both local (shadow) and remote (already applied).
-- ============================================================================


-- =============================================
-- PART 1: TABLE RENAMES
-- =============================================

-- 1a. deals_clerk_orgs -> deal_clerk_orgs
ALTER TABLE IF EXISTS public.deals_clerk_orgs RENAME TO deal_clerk_orgs;

-- 1b. term_sheet_templates -> document_templates
-- Note: init_schema already creates document_templates. Drop it first so rename succeeds.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'term_sheet_templates') THEN
    DROP TABLE IF EXISTS public.document_templates CASCADE;
    ALTER TABLE public.term_sheet_templates RENAME TO document_templates;
  END IF;
END $$;

-- 1c. term_sheet_template_fields -> document_template_fields
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'term_sheet_template_fields') THEN
    DROP TABLE IF EXISTS public.document_template_fields CASCADE;
    ALTER TABLE public.term_sheet_template_fields RENAME TO document_template_fields;
  END IF;
END $$;


-- =============================================
-- PART 2: CREATE UNTRACKED TABLES
-- Ordered by foreign-key dependency tiers.
-- =============================================


-- ─── TIER 0: No FK deps on other new tables ────────────────────────────

-- 1. actions
CREATE TABLE IF NOT EXISTS public.actions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    name text NOT NULL,
    description text,
    workflow_data jsonb DEFAULT '{}'::jsonb,
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- 2. input_categories
CREATE TABLE IF NOT EXISTS public.input_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category text,
    created_at timestamptz DEFAULT now() NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    organization_id uuid
);

-- 3. input_logic
CREATE TABLE IF NOT EXISTS public.input_logic (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type text,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- 4. organization_member_roles
CREATE TABLE IF NOT EXISTS public.organization_member_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id uuid,
    role_code text NOT NULL,
    role_name text NOT NULL,
    description text,
    is_active boolean DEFAULT true,
    display_order integer,
    created_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS organization_member_roles_unique_global
    ON public.organization_member_roles (role_code) WHERE organization_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS organization_member_roles_unique_per_org
    ON public.organization_member_roles (organization_id, role_code) WHERE organization_id IS NOT NULL;

-- 5. llama_document_chunks_vs
CREATE TABLE IF NOT EXISTS public.llama_document_chunks_vs (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    content text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    embedding public.vector(1536),
    created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS llama_chunks_embedding_hnsw_idx
    ON public.llama_document_chunks_vs USING hnsw (embedding public.vector_cosine_ops);

CREATE INDEX IF NOT EXISTS llama_chunks_metadata_gin_idx
    ON public.llama_document_chunks_vs USING gin (metadata);

-- 6. llama_document_parsed
CREATE TABLE IF NOT EXISTS public.llama_document_parsed (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint,
    status text,
    created_at timestamptz DEFAULT now() NOT NULL,
    llama_id text,
    llama_project_id text
);

CREATE INDEX IF NOT EXISTS llama_document_parsed_status_idx
    ON public.llama_document_parsed (status);

-- 7. workflow_executions
CREATE TABLE IF NOT EXISTS public.workflow_executions (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    workflow_id text NOT NULL,
    user_id text NOT NULL,
    organization_id uuid NOT NULL,
    status text DEFAULT 'running'::text NOT NULL,
    input jsonb,
    output jsonb,
    error text,
    started_at timestamptz DEFAULT now() NOT NULL,
    completed_at timestamptz,
    duration text
);

CREATE INDEX IF NOT EXISTS idx_workflow_executions_user_id
    ON public.workflow_executions (user_id);

CREATE INDEX IF NOT EXISTS idx_workflow_executions_workflow_id
    ON public.workflow_executions (workflow_id);

-- 8. application_appraisal
CREATE TABLE IF NOT EXISTS public.application_appraisal (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    application_id uuid NOT NULL UNIQUE,
    organization_id uuid NOT NULL,
    lender text,
    investor text,
    transaction_type text,
    loan_type text,
    loan_type_other text,
    loan_number text,
    priority text,
    borrower_name text,
    borrower_email text,
    borrower_phone text,
    borrower_alt_phone text,
    property_type text,
    occupancy_type text,
    property_address text,
    property_city text,
    property_state text,
    property_zip text,
    property_county text,
    contact_person text,
    contact_name text,
    contact_email text,
    contact_phone text,
    other_access_info text,
    product text,
    loan_amount text,
    sales_price text,
    due_date date,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_application_appraisal_app
    ON public.application_appraisal (application_id);

-- 9. application_background
CREATE TABLE IF NOT EXISTS public.application_background (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    application_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    entity_id uuid,
    borrower_id uuid,
    party_index integer DEFAULT 0 NOT NULL,
    is_entity boolean DEFAULT false NOT NULL,
    glb text,
    dppa text,
    voter text,
    entity_name text,
    entity_type text,
    ein text,
    state_of_formation text,
    date_of_formation date,
    first_name text,
    middle_initial text,
    last_name text,
    date_of_birth date,
    email text,
    phone text,
    street text,
    city text,
    state text,
    zip text,
    county text,
    province text,
    country text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE (application_id, party_index)
);

CREATE INDEX IF NOT EXISTS idx_application_background_app
    ON public.application_background (application_id);

-- 10. application_credit
CREATE TABLE IF NOT EXISTS public.application_credit (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    application_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    borrower_id uuid,
    guarantor_index integer DEFAULT 0 NOT NULL,
    pull_type text DEFAULT 'soft'::text,
    include_tu boolean DEFAULT true,
    include_ex boolean DEFAULT true,
    include_eq boolean DEFAULT true,
    first_name text,
    last_name text,
    date_of_birth date,
    street text,
    city text,
    state text,
    zip text,
    county text,
    prev_street text,
    prev_city text,
    prev_state text,
    prev_zip text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE (application_id, guarantor_index)
);

CREATE INDEX IF NOT EXISTS idx_application_credit_app
    ON public.application_credit (application_id);

-- 11. appraisal_amcs
CREATE TABLE IF NOT EXISTS public.appraisal_amcs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id uuid NOT NULL,
    name text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.appraisal_amcs IS 'Lookup table for Appraisal Management Companies per org';

CREATE INDEX IF NOT EXISTS idx_appraisal_amcs_org
    ON public.appraisal_amcs (organization_id);

-- 12. background_reports
CREATE TABLE IF NOT EXISTS public.background_reports (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    organization_id uuid NOT NULL,
    borrower_id uuid,
    entity_id uuid,
    is_entity boolean DEFAULT false NOT NULL,
    report_type text,
    status text DEFAULT 'pending'::text,
    report_date timestamptz,
    storage_path text,
    file_name text,
    file_size bigint,
    file_type text,
    notes text,
    created_by text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.background_reports IS 'Standalone background check reports linked to borrowers or entities';

CREATE INDEX IF NOT EXISTS idx_background_reports_borrower
    ON public.background_reports (borrower_id);

CREATE INDEX IF NOT EXISTS idx_background_reports_entity
    ON public.background_reports (entity_id);

CREATE INDEX IF NOT EXISTS idx_background_reports_org
    ON public.background_reports (organization_id);

-- 13. credit_report_data_links
CREATE TABLE IF NOT EXISTS public.credit_report_data_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_report_id uuid NOT NULL,
    aggregator text DEFAULT 'xactus'::text NOT NULL,
    aggregator_data_id uuid NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE (credit_report_id, aggregator)
);

COMMENT ON TABLE public.credit_report_data_links IS 'Links credit_reports to aggregator-specific data tables (xactus, etc.)';

CREATE INDEX IF NOT EXISTS idx_crdl_aggregator_data
    ON public.credit_report_data_links (aggregator_data_id);

CREATE INDEX IF NOT EXISTS idx_crdl_credit_report
    ON public.credit_report_data_links (credit_report_id);

-- 14. deal_entity
CREATE TABLE IF NOT EXISTS public.deal_entity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    deal_id uuid,
    entity_id uuid,
    entity_name text,
    entity_type text,
    ein text,
    date_formed date,
    address_line1 text,
    address_line2 text,
    city text,
    state text,
    zip text,
    county text,
    state_formed text,
    members integer
);

CREATE INDEX IF NOT EXISTS idx_deal_entity_deal_id
    ON public.deal_entity (deal_id);

-- 15. deal_entity_owners
CREATE TABLE IF NOT EXISTS public.deal_entity_owners (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id uuid,
    entity_id uuid,
    borrower_id uuid,
    entity_owner_id uuid,
    name text,
    title text,
    member_type text,
    ownership_percent numeric,
    address text,
    ssn_encrypted text,
    ssn_last4 text,
    ein text,
    created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_deal_entity_owners_deal_id
    ON public.deal_entity_owners (deal_id);

-- 16. deal_clerk_orgs (renamed from deals_clerk_orgs above; create if fresh DB)
CREATE TABLE IF NOT EXISTS public.deal_clerk_orgs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id uuid NOT NULL,
    clerk_org_id uuid NOT NULL,
    UNIQUE (deal_id, clerk_org_id)
);

CREATE INDEX IF NOT EXISTS idx_deal_orgs_clerk_org_id
    ON public.deal_clerk_orgs (clerk_org_id);

CREATE INDEX IF NOT EXISTS idx_deal_orgs_deal_id
    ON public.deal_clerk_orgs (deal_id);

-- 17. deal_document_ai_chat
CREATE TABLE IF NOT EXISTS public.deal_document_ai_chat (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_document_id bigint,
    user_id text,
    user_type text,
    message text,
    created_at timestamptz DEFAULT now() NOT NULL,
    citations jsonb
);

COMMENT ON COLUMN public.deal_document_ai_chat.citations IS 'Stores citation data for agent messages: [{page, bbox: {x,y,w,h}, snippet, docId, chunkId, whyRelevant}]';

-- 18. deal_document_ai_condition
CREATE TABLE IF NOT EXISTS public.deal_document_ai_condition (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type_ai_condition bigint,
    deal_document_id bigint,
    response json,
    ai_value boolean,
    approved_value boolean,
    rejected boolean,
    user_id text,
    created_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE (deal_document_id, document_type_ai_condition)
);

-- 19. deal_document_ai_input
CREATE TABLE IF NOT EXISTS public.deal_document_ai_input (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type_ai_input_id bigint,
    deal_document_id bigint,
    response json,
    ai_value text,
    approved_value text,
    rejected boolean,
    user_id text,
    created_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE (deal_document_id, document_type_ai_input_id)
);

-- 20. document_template_fields (renamed from term_sheet_template_fields above; create if fresh DB)
CREATE TABLE IF NOT EXISTS public.document_template_fields (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    template_id uuid NOT NULL,
    name text NOT NULL,
    field_type text NOT NULL,
    required boolean DEFAULT false NOT NULL,
    position integer DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.document_template_fields IS 'Stores custom fields for document templates with their types, required status, and display order';

CREATE INDEX IF NOT EXISTS idx_term_sheet_template_fields_position
    ON public.document_template_fields (template_id, position);

CREATE INDEX IF NOT EXISTS idx_term_sheet_template_fields_template_id
    ON public.document_template_fields (template_id);

-- 21. workflow_execution_logs
CREATE TABLE IF NOT EXISTS public.workflow_execution_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    execution_id uuid NOT NULL,
    node_id text NOT NULL,
    node_name text,
    node_type text,
    status text DEFAULT 'pending'::text NOT NULL,
    input jsonb,
    output jsonb,
    error text,
    started_at timestamptz,
    completed_at timestamptz,
    duration text
);

CREATE INDEX IF NOT EXISTS idx_workflow_execution_logs_execution_id
    ON public.workflow_execution_logs (execution_id);

-- 22. workflow_integrations
CREATE TABLE IF NOT EXISTS public.workflow_integrations (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    organization_id uuid NOT NULL,
    user_id text NOT NULL,
    type text NOT NULL,
    name text,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE (organization_id, user_id, type, name)
);

CREATE INDEX IF NOT EXISTS idx_workflow_integrations_org_user
    ON public.workflow_integrations (organization_id, user_id);

CREATE INDEX IF NOT EXISTS idx_workflow_integrations_type
    ON public.workflow_integrations (type);


-- ─── TIER 1: FK deps on Tier 0 new tables ──────────────────────────────

-- 23. inputs (FK -> input_categories)
CREATE TABLE IF NOT EXISTS public.inputs (
    id bigint NOT NULL PRIMARY KEY,
    category_id bigint,
    category text,
    input_label text,
    input_type text,
    dropdown_options json,
    created_at timestamptz DEFAULT now() NOT NULL,
    input_code text NOT NULL UNIQUE,
    display_order integer DEFAULT 0 NOT NULL,
    starred boolean DEFAULT false NOT NULL,
    organization_id uuid,
    linked_table text,
    linked_column text
);

-- Create sequence for inputs.id (matches remote)
CREATE SEQUENCE IF NOT EXISTS public.inputs_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER SEQUENCE public.inputs_id_seq OWNED BY public.inputs.id;

-- Set default only if not already set
DO $$ BEGIN
  ALTER TABLE ONLY public.inputs ALTER COLUMN id SET DEFAULT nextval('public.inputs_id_seq'::regclass);
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

COMMENT ON COLUMN public.inputs.linked_table IS 'Source table for database-linked inputs (e.g. borrowers, entities, property)';
COMMENT ON COLUMN public.inputs.linked_column IS 'Source column for database-linked inputs (e.g. fico_score, entity_name)';

CREATE INDEX IF NOT EXISTS idx_inputs_input_code
    ON public.inputs (input_code);

-- 24. background_report_applications (FK -> applications, background_reports)
CREATE TABLE IF NOT EXISTS public.background_report_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    background_report_id uuid NOT NULL,
    application_id uuid NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE (background_report_id, application_id)
);

COMMENT ON TABLE public.background_report_applications IS 'Junction table linking background reports to applications (many-to-many)';

CREATE INDEX IF NOT EXISTS idx_bra_application
    ON public.background_report_applications (application_id);

CREATE INDEX IF NOT EXISTS idx_bra_report
    ON public.background_report_applications (background_report_id);


-- ─── TIER 2: FK deps on Tier 1 ─────────────────────────────────────────

-- 25. input_logic_conditions (FK -> inputs, input_logic)
CREATE TABLE IF NOT EXISTS public.input_logic_conditions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_logic_id bigint,
    operator text,
    value text,
    created_at timestamptz DEFAULT now() NOT NULL,
    value_type text DEFAULT 'value'::text,
    value_expression text,
    field bigint,
    value_field bigint
);

-- 26. input_logic_actions (FK -> inputs, input_logic)
CREATE TABLE IF NOT EXISTS public.input_logic_actions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_logic_id bigint,
    created_at timestamptz DEFAULT now() NOT NULL,
    value_type text,
    value_visible boolean,
    value_required boolean,
    value_text text,
    value_expression text,
    input_id bigint,
    value_field bigint
);

-- 27. input_stepper (FK -> inputs)
CREATE TABLE IF NOT EXISTS public.input_stepper (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    step_order text[],
    input_id bigint
);

COMMENT ON COLUMN public.input_stepper.step_order IS 'Ordered array of dropdown option values defining step sequence';

-- 28. deal_inputs (FK -> deals, inputs)
CREATE TABLE IF NOT EXISTS public.deal_inputs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id uuid,
    input_type text,
    value_text text,
    value_numeric numeric,
    value_date date,
    value_array json,
    value_bool boolean,
    created_at timestamptz DEFAULT now() NOT NULL,
    input_id bigint,
    linked_record_id text,
    UNIQUE (deal_id, input_id)
);

COMMENT ON COLUMN public.deal_inputs.linked_record_id IS 'PK of the selected record in the linked table';

-- 29. deal_calendar_events (FK -> deals, inputs)
CREATE TABLE IF NOT EXISTS public.deal_calendar_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id uuid,
    event_title text,
    event_description text,
    all_day boolean,
    created_at timestamptz DEFAULT now() NOT NULL,
    etiquette text,
    event_date date NOT NULL,
    event_time time without time zone,
    deal_input_id bigint
);

CREATE INDEX IF NOT EXISTS idx_deal_calendar_events_deal_date
    ON public.deal_calendar_events (deal_id, event_date);

CREATE INDEX IF NOT EXISTS idx_deal_calendar_events_deal_id
    ON public.deal_calendar_events (deal_id);

CREATE INDEX IF NOT EXISTS idx_deal_calendar_events_deal_input_id
    ON public.deal_calendar_events (deal_input_id) WHERE deal_input_id IS NOT NULL;


-- ─── TIER 3: FK deps on Tier 2 ─────────────────────────────────────────

-- 30. deal_stepper (FK -> deals, input_stepper)
CREATE TABLE IF NOT EXISTS public.deal_stepper (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id uuid NOT NULL UNIQUE,
    input_stepper_id bigint NOT NULL,
    current_step text NOT NULL,
    step_order text[] NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- 31. deal_borrower (FK -> deal_entity, deals)
CREATE TABLE IF NOT EXISTS public.deal_borrower (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    deal_id uuid NOT NULL,
    vesting_type text,
    deal_entity_id bigint NOT NULL,
    deal_guarantor_ids bigint[] DEFAULT '{}'::bigint[]
);

CREATE INDEX IF NOT EXISTS idx_deal_borrower_deal_entity_id
    ON public.deal_borrower (deal_entity_id);

CREATE INDEX IF NOT EXISTS idx_deal_borrower_deal_id
    ON public.deal_borrower (deal_id);

CREATE INDEX IF NOT EXISTS idx_deal_borrower_guarantors_gin
    ON public.deal_borrower USING gin (deal_guarantor_ids);


-- =============================================
-- PART 3: FOREIGN KEY CONSTRAINTS
-- Wrapped in exception handlers for idempotency.
-- =============================================

DO $$ BEGIN

-- organization_member_roles -> organizations
ALTER TABLE ONLY public.organization_member_roles
    ADD CONSTRAINT organization_member_roles_organization_id_fkey
    FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- application_appraisal -> applications
ALTER TABLE ONLY public.application_appraisal
    ADD CONSTRAINT application_appraisal_application_id_fkey
    FOREIGN KEY (application_id) REFERENCES public.applications(loan_id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.application_appraisal
    ADD CONSTRAINT application_appraisal_organization_id_fkey
    FOREIGN KEY (organization_id) REFERENCES public.organizations(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- application_background -> applications, borrowers, entities, organizations
ALTER TABLE ONLY public.application_background
    ADD CONSTRAINT application_background_application_id_fkey
    FOREIGN KEY (application_id) REFERENCES public.applications(loan_id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.application_background
    ADD CONSTRAINT application_background_borrower_id_fkey
    FOREIGN KEY (borrower_id) REFERENCES public.borrowers(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.application_background
    ADD CONSTRAINT application_background_entity_id_fkey
    FOREIGN KEY (entity_id) REFERENCES public.entities(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.application_background
    ADD CONSTRAINT application_background_organization_id_fkey
    FOREIGN KEY (organization_id) REFERENCES public.organizations(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- application_credit -> applications, borrowers, organizations
ALTER TABLE ONLY public.application_credit
    ADD CONSTRAINT application_credit_application_id_fkey
    FOREIGN KEY (application_id) REFERENCES public.applications(loan_id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.application_credit
    ADD CONSTRAINT application_credit_borrower_id_fkey
    FOREIGN KEY (borrower_id) REFERENCES public.borrowers(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.application_credit
    ADD CONSTRAINT application_credit_organization_id_fkey
    FOREIGN KEY (organization_id) REFERENCES public.organizations(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- appraisal_amcs -> organizations
ALTER TABLE ONLY public.appraisal_amcs
    ADD CONSTRAINT appraisal_amcs_organization_id_fkey
    FOREIGN KEY (organization_id) REFERENCES public.organizations(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- background_reports -> borrowers, entities, organizations
ALTER TABLE ONLY public.background_reports
    ADD CONSTRAINT background_reports_borrower_id_fkey
    FOREIGN KEY (borrower_id) REFERENCES public.borrowers(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.background_reports
    ADD CONSTRAINT background_reports_entity_id_fkey
    FOREIGN KEY (entity_id) REFERENCES public.entities(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.background_reports
    ADD CONSTRAINT background_reports_organization_id_fkey
    FOREIGN KEY (organization_id) REFERENCES public.organizations(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- credit_report_data_links -> credit_reports
ALTER TABLE ONLY public.credit_report_data_links
    ADD CONSTRAINT credit_report_data_links_credit_report_id_fkey
    FOREIGN KEY (credit_report_id) REFERENCES public.credit_reports(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- deal_entity -> deals, entities
ALTER TABLE ONLY public.deal_entity
    ADD CONSTRAINT deal_entity_deal_id_fkey
    FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_entity
    ADD CONSTRAINT deal_entity_entity_id_fkey
    FOREIGN KEY (entity_id) REFERENCES public.entities(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- deal_entity_owners -> borrowers, deals, entities (x2)
ALTER TABLE ONLY public.deal_entity_owners
    ADD CONSTRAINT deal_entity_owners_borrower_id_fkey
    FOREIGN KEY (borrower_id) REFERENCES public.borrowers(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_entity_owners
    ADD CONSTRAINT deal_entity_owners_deal_id_fkey
    FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_entity_owners
    ADD CONSTRAINT deal_entity_owners_entity_id_fkey
    FOREIGN KEY (entity_id) REFERENCES public.entities(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_entity_owners
    ADD CONSTRAINT deal_entity_owners_entity_owner_id_fkey
    FOREIGN KEY (entity_owner_id) REFERENCES public.entities(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- deal_clerk_orgs -> organizations, deals
ALTER TABLE ONLY public.deal_clerk_orgs
    ADD CONSTRAINT deal_clerk_orgs_clerk_org_id_fkey
    FOREIGN KEY (clerk_org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_clerk_orgs
    ADD CONSTRAINT deal_clerk_orgs_deal_id_fkey
    FOREIGN KEY (deal_id) REFERENCES public.deals(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- deal_document_ai_chat -> deal_documents
ALTER TABLE ONLY public.deal_document_ai_chat
    ADD CONSTRAINT deal_document_ai_chat_deal_document_id_fkey
    FOREIGN KEY (deal_document_id) REFERENCES public.deal_documents(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- deal_document_ai_condition -> deal_documents, document_type_ai_condition
ALTER TABLE ONLY public.deal_document_ai_condition
    ADD CONSTRAINT deal_document_ai_condition_deal_document_id_fkey
    FOREIGN KEY (deal_document_id) REFERENCES public.deal_documents(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_document_ai_condition
    ADD CONSTRAINT deal_document_ai_condition_document_type_ai_condition_fkey
    FOREIGN KEY (document_type_ai_condition) REFERENCES public.document_type_ai_condition(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- deal_document_ai_input -> deal_documents, document_type_ai_input
ALTER TABLE ONLY public.deal_document_ai_input
    ADD CONSTRAINT deal_document_ai_input_deal_document_id_fkey
    FOREIGN KEY (deal_document_id) REFERENCES public.deal_documents(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_document_ai_input
    ADD CONSTRAINT deal_document_ai_input_document_type_ai_input_id_fkey
    FOREIGN KEY (document_type_ai_input_id) REFERENCES public.document_type_ai_input(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- document_template_fields -> document_templates
ALTER TABLE ONLY public.document_template_fields
    ADD CONSTRAINT term_sheet_template_fields_template_id_fkey
    FOREIGN KEY (template_id) REFERENCES public.document_templates(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- workflow_execution_logs -> workflow_executions
ALTER TABLE ONLY public.workflow_execution_logs
    ADD CONSTRAINT workflow_execution_logs_execution_id_fkey
    FOREIGN KEY (execution_id) REFERENCES public.workflow_executions(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- workflow_integrations -> organizations
ALTER TABLE ONLY public.workflow_integrations
    ADD CONSTRAINT workflow_integrations_organization_id_fkey
    FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- inputs -> input_categories
ALTER TABLE ONLY public.inputs
    ADD CONSTRAINT inputs_category_id_fkey
    FOREIGN KEY (category_id) REFERENCES public.input_categories(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- background_report_applications -> applications, background_reports
ALTER TABLE ONLY public.background_report_applications
    ADD CONSTRAINT background_report_applications_application_id_fkey
    FOREIGN KEY (application_id) REFERENCES public.applications(loan_id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.background_report_applications
    ADD CONSTRAINT background_report_applications_background_report_id_fkey
    FOREIGN KEY (background_report_id) REFERENCES public.background_reports(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- input_logic_conditions -> inputs, input_logic
ALTER TABLE ONLY public.input_logic_conditions
    ADD CONSTRAINT input_logic_conditions_field_fkey
    FOREIGN KEY (field) REFERENCES public.inputs(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.input_logic_conditions
    ADD CONSTRAINT input_logic_conditions_input_logic_id_fkey
    FOREIGN KEY (input_logic_id) REFERENCES public.input_logic(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.input_logic_conditions
    ADD CONSTRAINT input_logic_conditions_value_field_fkey
    FOREIGN KEY (value_field) REFERENCES public.inputs(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- input_logic_actions -> inputs, input_logic
ALTER TABLE ONLY public.input_logic_actions
    ADD CONSTRAINT input_logic_actions_input_id_fkey
    FOREIGN KEY (input_id) REFERENCES public.inputs(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.input_logic_actions
    ADD CONSTRAINT input_logic_actions_input_logic_id_fkey
    FOREIGN KEY (input_logic_id) REFERENCES public.input_logic(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.input_logic_actions
    ADD CONSTRAINT input_logic_actions_value_field_fkey
    FOREIGN KEY (value_field) REFERENCES public.inputs(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- input_stepper -> inputs
ALTER TABLE ONLY public.input_stepper
    ADD CONSTRAINT input_stepper_input_id_fkey
    FOREIGN KEY (input_id) REFERENCES public.inputs(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- deal_inputs -> deals, inputs
ALTER TABLE ONLY public.deal_inputs
    ADD CONSTRAINT deal_inputs_deal_id_fkey
    FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_inputs
    ADD CONSTRAINT deal_inputs_input_id_fkey
    FOREIGN KEY (input_id) REFERENCES public.inputs(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- deal_calendar_events -> deals, inputs
ALTER TABLE ONLY public.deal_calendar_events
    ADD CONSTRAINT deal_calendar_events_deal_id_fkey
    FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_calendar_events
    ADD CONSTRAINT deal_calendar_events_deal_input_id_fkey
    FOREIGN KEY (deal_input_id) REFERENCES public.inputs(id);
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- deal_stepper -> deals, input_stepper
ALTER TABLE ONLY public.deal_stepper
    ADD CONSTRAINT deal_stepper_deal_id_fkey
    FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_stepper
    ADD CONSTRAINT deal_stepper_input_stepper_id_fkey
    FOREIGN KEY (input_stepper_id) REFERENCES public.input_stepper(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
-- deal_borrower -> deal_entity, deals
ALTER TABLE ONLY public.deal_borrower
    ADD CONSTRAINT deal_borrower_deal_entity_id_fkey
    FOREIGN KEY (deal_entity_id) REFERENCES public.deal_entity(id) ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;

DO $$ BEGIN
ALTER TABLE ONLY public.deal_borrower
    ADD CONSTRAINT deal_borrower_deal_id_fkey
    FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_table THEN NULL;
END $$;


-- =============================================
-- PART 4: VERIFICATION
-- =============================================
DO $$
DECLARE
    v_count integer;
BEGIN
    SELECT count(*)
    INTO v_count
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name IN (
        'actions', 'application_appraisal', 'application_background', 'application_credit',
        'appraisal_amcs', 'background_report_applications', 'background_reports',
        'credit_report_data_links', 'deal_borrower', 'deal_calendar_events',
        'deal_clerk_orgs', 'deal_document_ai_chat', 'deal_document_ai_condition',
        'deal_document_ai_input', 'deal_entity', 'deal_entity_owners', 'deal_inputs',
        'deal_stepper', 'document_template_fields', 'document_templates',
        'input_categories', 'input_logic', 'input_logic_actions', 'input_logic_conditions',
        'input_stepper', 'inputs', 'llama_document_chunks_vs', 'llama_document_parsed',
        'organization_member_roles', 'workflow_execution_logs', 'workflow_executions',
        'workflow_integrations'
      );
    RAISE NOTICE 'Migration verified: % / 32 expected tables exist', v_count;
END $$;
