-- =====================================================
-- Migration 2: Document Categories
-- Date: 2026-01-28
-- Description: Create document categorization system
-- Dependencies: None
-- Breaking Changes: None
-- Risk Level: LOW
-- =====================================================

BEGIN;

-- =====================================================
-- Create document_status enum
-- =====================================================
DO $$ BEGIN
  CREATE TYPE public.document_status AS ENUM (
    'draft', 
    'pending', 
    'approved', 
    'rejected', 
    'archived'
  );
EXCEPTION
  WHEN duplicate_object THEN 
    RAISE NOTICE 'document_status enum already exists, skipping';
END $$;

-- =====================================================
-- Create document_categories table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.document_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  description text NULL,
  storage_folder text NOT NULL,
  icon text NULL,
  default_display_order integer NULL,
  is_active boolean NULL DEFAULT true,
  is_internal_only boolean NULL DEFAULT false,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT document_categories_pkey PRIMARY KEY (id),
  CONSTRAINT document_categories_code_key UNIQUE (code)
) TABLESPACE pg_default;

-- =====================================================
-- Enable RLS
-- =====================================================
ALTER TABLE public.document_categories ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- Create RLS policies
-- =====================================================
CREATE POLICY "All authenticated users can view active categories"
  ON public.document_categories
  FOR SELECT
  TO authenticated
  USING (is_active = true);

CREATE POLICY "Internal admins can manage categories"
  ON public.document_categories
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE clerk_user_id = auth.uid()::text 
        AND is_internal_yn = true
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE clerk_user_id = auth.uid()::text 
        AND is_internal_yn = true
    )
  );

-- =====================================================
-- Populate with default categories
-- =====================================================
INSERT INTO public.document_categories (code, name, description, storage_folder, icon, default_display_order, is_active)
VALUES 
  ('financial', 'Financial Documents', 'Bank statements, tax returns, income verification', 'financial', 'dollar-sign', 10, true),
  ('legal', 'Legal Documents', 'Contracts, agreements, legal notices', 'legal', 'file-text', 20, true),
  ('identity', 'Identity Documents', 'Driver licenses, passports, SSN cards', 'identity', 'user', 30, true),
  ('property', 'Property Documents', 'Deeds, titles, property records', 'property', 'home', 40, true),
  ('inspection', 'Inspection Reports', 'Property inspection reports', 'inspection', 'clipboard', 50, true),
  ('appraisal', 'Appraisals', 'Property appraisal reports', 'appraisal', 'trending-up', 60, true),
  ('insurance', 'Insurance Documents', 'Insurance policies and certificates', 'insurance', 'shield', 70, true),
  ('other', 'Other Documents', 'Miscellaneous documents', 'other', 'folder', 99, true)
ON CONFLICT (code) DO NOTHING;

-- =====================================================
-- Verification
-- =====================================================
DO $$
DECLARE
  v_count integer;
BEGIN
  -- Check table exists
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_name = 'document_categories'
  ) THEN
    RAISE EXCEPTION 'Migration 2 failed: document_categories table not created';
  END IF;
  
  -- Check enum exists
  IF NOT EXISTS (
    SELECT 1 FROM pg_type 
    WHERE typname = 'document_status'
  ) THEN
    RAISE EXCEPTION 'Migration 2 failed: document_status enum not created';
  END IF;
  
  -- Check categories were inserted
  SELECT COUNT(*) INTO v_count FROM public.document_categories;
  IF v_count < 8 THEN
    RAISE WARNING 'Migration 2: Expected 8 categories, found %', v_count;
  END IF;
  
  RAISE NOTICE 'Migration 2 completed successfully (% categories created)', v_count;
END $$;

COMMIT;

-- =====================================================
-- Post-migration notes:
-- - document_status enum created for workflow states
-- - document_categories table created with code as UNIQUE NOT NULL
-- - 8 default categories populated
-- - RLS enabled with read access for authenticated users
-- - Admins have full management access
-- =====================================================
