-- ============================================================================
-- Migration: Create background_reports and background_report_applications
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. background_reports - standalone background check records
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.background_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id),
  borrower_id uuid REFERENCES public.borrowers(id) ON DELETE SET NULL,
  entity_id uuid REFERENCES public.entities(id) ON DELETE SET NULL,
  is_entity boolean NOT NULL DEFAULT false,
  report_type text,
  status text DEFAULT 'pending',
  report_date timestamptz,
  storage_path text,
  file_name text,
  file_size bigint,
  file_type text,
  notes text,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.background_reports IS 'Standalone background check reports linked to borrowers or entities';

CREATE INDEX IF NOT EXISTS idx_background_reports_org ON public.background_reports(organization_id);
CREATE INDEX IF NOT EXISTS idx_background_reports_borrower ON public.background_reports(borrower_id);
CREATE INDEX IF NOT EXISTS idx_background_reports_entity ON public.background_reports(entity_id);

-- RLS
ALTER TABLE public.background_reports ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.background_reports TO authenticated;
GRANT ALL ON public.background_reports TO service_role;

CREATE POLICY "background_reports_select" ON public.background_reports
  FOR SELECT TO authenticated
  USING (organization_id = get_active_org_id());

CREATE POLICY "background_reports_insert" ON public.background_reports
  FOR INSERT TO authenticated
  WITH CHECK (organization_id = get_active_org_id());

CREATE POLICY "background_reports_update" ON public.background_reports
  FOR UPDATE TO authenticated
  USING (organization_id = get_active_org_id());

CREATE POLICY "background_reports_delete" ON public.background_reports
  FOR DELETE TO authenticated
  USING (organization_id = get_active_org_id());

-- Auto-update updated_at
CREATE OR REPLACE TRIGGER background_reports_updated_at
  BEFORE UPDATE ON public.background_reports
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();

-- ============================================================================
-- 2. background_report_applications - junction table (many-to-many)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.background_report_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  background_report_id uuid NOT NULL REFERENCES public.background_reports(id) ON DELETE CASCADE,
  application_id uuid NOT NULL REFERENCES public.applications(loan_id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT background_report_applications_unique UNIQUE (background_report_id, application_id)
);

CREATE INDEX IF NOT EXISTS idx_bra_report ON public.background_report_applications(background_report_id);
CREATE INDEX IF NOT EXISTS idx_bra_application ON public.background_report_applications(application_id);

COMMENT ON TABLE public.background_report_applications IS 'Junction table linking background reports to applications (many-to-many)';

-- RLS - join through background_reports for org scoping
ALTER TABLE public.background_report_applications ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.background_report_applications TO authenticated;
GRANT ALL ON public.background_report_applications TO service_role;

CREATE POLICY "bra_select" ON public.background_report_applications
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.background_reports br
    WHERE br.id = background_report_id
    AND br.organization_id = get_active_org_id()
  ));

CREATE POLICY "bra_insert" ON public.background_report_applications
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.background_reports br
    WHERE br.id = background_report_id
    AND br.organization_id = get_active_org_id()
  ));

CREATE POLICY "bra_delete" ON public.background_report_applications
  FOR DELETE TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.background_reports br
    WHERE br.id = background_report_id
    AND br.organization_id = get_active_org_id()
  ));

COMMIT;
