BEGIN;

-- Junction table linking document_files to credit_reports
CREATE TABLE IF NOT EXISTS public.document_files_credit_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  document_file_id bigint NOT NULL,
  credit_report_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  created_by text,
  CONSTRAINT document_files_credit_reports_pkey PRIMARY KEY (id),
  CONSTRAINT document_files_credit_reports_unique UNIQUE (document_file_id, credit_report_id),
  CONSTRAINT document_files_credit_reports_doc_fkey
    FOREIGN KEY (document_file_id) REFERENCES document_files(id) ON DELETE CASCADE,
  CONSTRAINT document_files_credit_reports_cr_fkey
    FOREIGN KEY (credit_report_id) REFERENCES credit_reports(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_doc_files_credit_reports_doc
  ON public.document_files_credit_reports USING btree (document_file_id);

CREATE INDEX IF NOT EXISTS idx_doc_files_credit_reports_cr
  ON public.document_files_credit_reports USING btree (credit_report_id);

ALTER TABLE public.document_files_credit_reports ENABLE ROW LEVEL SECURITY;

-- RLS: select if user can access the linked credit_report's org
CREATE POLICY "dfcr_select" ON public.document_files_credit_reports
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.credit_reports cr
    WHERE cr.id = credit_report_id
    AND cr.organization_id = get_active_org_id()
  ));

CREATE POLICY "dfcr_insert" ON public.document_files_credit_reports
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.credit_reports cr
    WHERE cr.id = credit_report_id
    AND cr.organization_id = get_active_org_id()
  ));

CREATE POLICY "dfcr_delete" ON public.document_files_credit_reports
  FOR DELETE TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.credit_reports cr
    WHERE cr.id = credit_report_id
    AND cr.organization_id = get_active_org_id()
  ));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.document_files_credit_reports TO authenticated;
GRANT ALL ON public.document_files_credit_reports TO service_role;

COMMIT;
