-- Rename xactus_data to credit_report_data_xactus
ALTER TABLE IF EXISTS "xactus_data" RENAME TO "credit_report_data_xactus";

-- Functions for triggers
create or replace function public.trg_ddp_from_deal_guarantors()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    -- docs directly linked to this guarantor
    insert into public.deal_document_participants (deal_id, document_file_id, source_table, source_pk)
    select new.deal_id, dfg.document_file_id, 'document_files_guarantors', dfg.id
    from public.document_files_guarantors dfg
    where dfg.guarantor_id = new.guarantor_id
    on conflict do nothing;

    -- docs linked to the borrower of this guarantor
    insert into public.deal_document_participants (deal_id, document_file_id, source_table, source_pk)
    select new.deal_id, dfb.document_file_id, 'document_files_borrowers', dfb.id
    from public.guarantor g
    join public.document_files_borrowers dfb
      on dfb.borrower_id = g.borrower_id
    where g.id = new.guarantor_id
    on conflict do nothing;

    return new;
  elsif tg_op = 'DELETE' then
    -- remove guarantor-linked ddp rows for this deal
    delete from public.deal_document_participants ddp
    where ddp.deal_id = old.deal_id
      and ddp.source_table = 'document_files_guarantors'
      and ddp.source_pk in (
        select dfg.id
        from public.document_files_guarantors dfg
        where dfg.guarantor_id = old.guarantor_id
      );

    -- remove borrower-linked ddp rows for this deal (borrower derived via this guarantor)
    delete from public.deal_document_participants ddp
    where ddp.deal_id = old.deal_id
      and ddp.source_table = 'document_files_borrowers'
      and ddp.source_pk in (
        select dfb.id
        from public.guarantor g
        join public.document_files_borrowers dfb
          on dfb.borrower_id = g.borrower_id
        where g.id = old.guarantor_id
      );

    return old;
  end if;

  return null;
end;
$$;

create or replace function public.trg_ddp_from_deal_property()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.deal_document_participants (deal_id, document_file_id, source_table, source_pk)
    select new.deal_id, dfp.document_file_id, 'document_files_properties', dfp.id
    from public.document_files_properties dfp
    where dfp.property_id = new.property_id
    on conflict do nothing;

    return new;
  elsif tg_op = 'DELETE' then
    delete from public.deal_document_participants ddp
    where ddp.deal_id = old.deal_id
      and ddp.source_table = 'document_files_properties'
      and ddp.source_pk in (
        select dfp.id
        from public.document_files_properties dfp
        where dfp.property_id = old.property_id
      );

    return old;
  end if;

  return null;
end;
$$;

create or replace function public.handle_property_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Create contact table
create table if not exists public.contact (
  id bigint generated by default as identity not null,
  first_name text null,
  last_name text null,
  email_address text null,
  cell_phone text null,
  home_phone text null,
  office_phone text null,
  portal_access boolean null default false,
  profile_picture text null,
  created_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  middle_name text null,
  name text GENERATED ALWAYS as (
    case
      when (
        (middle_name is not null)
        and (middle_name <> ''::text)
      ) then (
        (
          ((first_name || ' '::text) || middle_name) || ' '::text
        ) || last_name
      )
      else ((first_name || ' '::text) || last_name)
    end
  ) STORED null,
  constraint contact_pkey primary key (id)
) TABLESPACE pg_default;

create trigger handle_updated_at
before update on contact for each row
execute function public.trigger_set_timestamp();

-- Create guarantor table
create table if not exists public.guarantor (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  borrower_id text null,
  first_name text null,
  middle_name text null,
  last_name text null,
  email_address text null,
  cell_phone text null,
  home_phone text null,
  office_phone text null,
  primary_residence_address_street text null,
  primary_residence_address_suite_apt text null,
  primary_residence_address_city text null,
  primary_residence_address_state text null,
  primary_residence_address_state_long text null,
  primary_residence_address_postal_code text null,
  primary_residence_address_country text null,
  primary_residence_occupancy_start_date date null,
  primary_residence_ownership text null,
  previous_residence_address_street text null,
  previous_residence_address_suite_apt text null,
  previous_residence_address_city text null,
  previous_residence_address_state text null,
  previous_residence_address_state_long text null,
  previous_residence_address_postal_code text null,
  previous_residence_address_country text null,
  mailing_address_is_primary_residence boolean null,
  mailing_address_street text null,
  mailing_address_suite_apt text null,
  mailing_address_po_box text null,
  mailing_address_city text null,
  mailing_address_state text null,
  mailing_address_state_long text null,
  mailing_address_postal_code text null,
  mailing_address_country text null,
  date_of_birth date null,
  social_security_number text null,
  citizenship text null,
  marital_status text null,
  name text GENERATED ALWAYS as (
    case
      when (
        (middle_name is not null)
        and (middle_name <> ''::text)
      ) then (
        (
          ((first_name || ' '::text) || middle_name) || ' '::text
        ) || last_name
      )
      else ((first_name || ' '::text) || last_name)
    end
  ) STORED null,
  constraint guarantor_pkey primary key (id),
  constraint guarantor_borrower_id_fkey foreign KEY (borrower_id) references borrowers (display_id) on delete CASCADE
) TABLESPACE pg_default;

-- Create deal_guarantors table
create table if not exists public.deal_guarantors (
  id bigint generated by default as identity not null,
  deal_id uuid not null,
  guarantor_id bigint not null,
  is_primary boolean null default false,
  display_order integer null,
  notes text null,
  created_at timestamp with time zone null default now(),
  constraint deals_guarantors_pkey primary key (id),
  constraint deal_guarantors_unique unique (deal_id, guarantor_id),
  constraint deals_guarantors_deal_id_fkey foreign KEY (deal_id) references deals (id) on delete CASCADE,
  constraint deals_guarantors_guarantor_id_fkey foreign KEY (guarantor_id) references guarantor (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists deal_guarantors_deal_id_idx on public.deal_guarantors using btree (deal_id) TABLESPACE pg_default;
create index IF not exists deal_guarantors_guarantor_id_idx on public.deal_guarantors using btree (guarantor_id) TABLESPACE pg_default;
create index IF not exists idx_dg_guar on public.deal_guarantors using btree (guarantor_id, deal_id) TABLESPACE pg_default;

-- Trigger for deal_guarantors
create or replace trigger trg_ddp_deal_guarantors
after insert or delete on deal_guarantors for each row
execute function trg_ddp_from_deal_guarantors ();

-- Modify credit_reports
ALTER TABLE "credit_reports" ADD COLUMN IF NOT EXISTS "report_id" bigint;

-- Modify credit_report_data_xactus
ALTER TABLE "credit_report_data_xactus" ADD COLUMN IF NOT EXISTS "file_size" int8;
ALTER TABLE "credit_report_data_xactus" ADD COLUMN IF NOT EXISTS "file_type" text;
ALTER TABLE "credit_report_data_xactus" ADD COLUMN IF NOT EXISTS "uploaded_at" timestamptz;
ALTER TABLE "credit_report_data_xactus" ADD COLUMN IF NOT EXISTS "uploaded_by" text;

ALTER TABLE "credit_report_data_xactus" DROP COLUMN IF EXISTS "report_id";
ALTER TABLE "credit_report_data_xactus" ADD COLUMN "report_id" text;
ALTER TABLE "credit_report_data_xactus" ADD COLUMN IF NOT EXISTS "date_ordered" date;
ALTER TABLE "credit_report_data_xactus" ADD COLUMN IF NOT EXISTS "guarantor_id" bigint;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'credit_report_data_xactus_guarantor_id_fkey') THEN
        ALTER TABLE "credit_report_data_xactus" ADD CONSTRAINT "credit_report_data_xactus_guarantor_id_fkey" FOREIGN KEY ("guarantor_id") REFERENCES guarantor("id");
    END IF;
END $$;

-- Create deal_document_participants
create table if not exists public.deal_document_participants (
  deal_id uuid not null,
  document_file_id bigint not null,
  source_table text not null,
  source_pk bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint deal_document_participants_pkey primary key (
    deal_id,
    document_file_id,
    source_table,
    source_pk
  ),
  constraint deal_document_participants_deal_id_fkey foreign KEY (deal_id) references deals (id) on delete CASCADE,
  constraint deal_document_participants_document_file_id_fkey foreign KEY (document_file_id) references document_files (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_ddp_deal on public.deal_document_participants using btree (deal_id, document_file_id) TABLESPACE pg_default;
create index IF not exists idx_ddp_doc on public.deal_document_participants using btree (document_file_id) TABLESPACE pg_default;

-- Create property table
create table if not exists public.property (
  id bigint generated by default as identity not null,
  property_type text null, -- Changed from public.property_type
  year_built bigint null,
  sq_footage_gla_aiv bigint null,
  address_street text null,
  address_suite_apt text null,
  address_city text null,
  address_state text null, -- Changed from public.us_states
  address_postal_code text null,
  address_country text null default 'United States'::text,
  units smallint null,
  expense_annual_property_tax numeric null,
  expense_annual_insurance_hoi numeric null,
  expense_annual_insurance_flood numeric null,
  expense_annual_management numeric null,
  expense_annual_association_hoa numeric null,
  purchase_price numeric null,
  renovation_cost numeric null,
  renovation_completed date null,
  created_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  address text null,
  short_term_rental text null, -- Changed from public.yes_no
  declining_market text null, -- Changed from public.yes_no
  rural text null, -- Changed from public.yes_no
  flood_zone text null, -- Changed from public.yes_no
  recently_renovated text null, -- Changed from public.yes_no
  purchase_date date null,
  rehab_completed_post_acquisition numeric null,
  value_aiv_estimate numeric null,
  hoa_contact_phone text null,
  hoa_contact_person text null,
  hoa_contact_email text null,
  inspection text null, -- Changed from public.yes_no
  sq_footage_lot_aiv bigint null,
  value_aiv_appraised numeric null,
  value_arv_estimate numeric null,
  value_arv_appraised numeric null,
  warrantability text null, -- Changed from public.warrantability
  latitude numeric null,
  longitude numeric null,
  hoa_contact bigint null,
  address_state_long text null, -- Changed from public.us_states_long
  bedrooms_aiv numeric null,
  bedrooms_arv numeric null,
  bathrooms_aiv numeric null,
  bathrooms_arv numeric null,
  sq_footage_gla_arv bigint null,
  sq_footage_lot_arv bigint null,
  address_county text null,
  hoa_name text null,
  occupancy text null, -- Changed from public.property_occupancy
  income_monthly_gross_rent numeric null,
  income_monthly_fair_market_rent numeric null,
  sale_price numeric null,
  sale_date date null,
  photo_url text null,
  constraint property_pkey primary key (id),
  constraint property_hoa_contact_fkey foreign KEY (hoa_contact) references contact (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

-- Triggers for property
-- Commented out because function handle_property_changes does not exist
-- create or replace trigger handle_property_changes_trigger
-- after update on property for EACH row
-- execute FUNCTION handle_property_changes ();

create or replace trigger handle_updated_at BEFORE
update on property for EACH row
execute FUNCTION public.trigger_set_timestamp();

-- Create deal_property table
create table if not exists public.deal_property (
  id bigint generated by default as identity not null,
  deal_id uuid not null,
  property_id bigint not null,
  constraint deal_property_pkey primary key (id),
  constraint public_deal_property_deal_id_fkey foreign KEY (deal_id) references deals (id) on delete CASCADE,
  constraint public_deal_property_property_id_fkey foreign KEY (property_id) references property (id)
) TABLESPACE pg_default;

create index IF not exists idx_dp_prop on public.deal_property using btree (property_id, deal_id) TABLESPACE pg_default;

-- Trigger for deal_property
create or replace trigger trg_ddp_deal_property
after insert or delete on deal_property for each row
execute function trg_ddp_from_deal_property ();

-- Create appraisal table
create table if not exists public.appraisal (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  date_report_effective date null,
  date_report_expiration date null,
  updated_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  property_id bigint null,
  deal_id uuid null,
  document_id bigint null,
  date_report_ordered date null,
  date_report_received date null,
  date_inspection_completed date null,
  date_inspection_scheduled date null,
  value_conclusion_as_is numeric null,
  value_conclusion_as_repaired numeric null,
  value_conclusion_fair_market_rent numeric null,
  file_number_amc text null,
  file_number text null,
  co_appraisal uuid null,
  co_amc uuid null,
  appraiser_id bigint null,
  date_amc_vendor_assign timestamp with time zone null,
  date_amc_vendor_accept timestamp with time zone null,
  order_type text null,
  order_status text null,
  constraint appraisal_pkey primary key (id),
  constraint appraisal_co_amc_fkey foreign KEY (co_amc) references entities (id) on delete set null,
  constraint appraisal_co_appraisal_fkey foreign KEY (co_appraisal) references entities (id) on delete set null,
  constraint appraisal_appraiser_id_fkey foreign KEY (appraiser_id) references contact (id) on delete set null,
  constraint appraisal_document_id_fkey foreign KEY (document_id) references document_files (id) on delete set null,
  constraint appraisal_property_id_fkey foreign KEY (property_id) references property (id) on delete set null,
  constraint appraisal_deal_id_fkey foreign KEY (deal_id) references deals (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_appraisal_doc on public.appraisal using btree (document_id, deal_id, property_id) TABLESPACE pg_default;
