-- ============================================================
-- LANDING PAGE TEMPLATES TABLE
-- For GrapesJS-based landing page builder
-- ============================================================

create table if not exists public.landing_page_templates (
  id bigint generated by default as identity primary key,

  organization_id uuid not null
    references public.organizations(id) on delete restrict,

  user_id text not null,

  name text not null default 'Untitled Landing Page',

  status text not null default 'draft'
    check (status in ('draft', 'published')),

  html_content text not null default '',
  gjs_data jsonb not null default '{}'::jsonb,

  slug text null,
  published_at timestamptz null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- RLS
-- ============================================================

alter table public.landing_page_templates enable row level security;

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

drop trigger if exists landing_page_templates_updated_at on public.landing_page_templates;

create trigger landing_page_templates_updated_at
before update on public.landing_page_templates
for each row
execute function public.set_current_timestamp_updated_at();

-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists landing_page_templates_organization_id_idx
on public.landing_page_templates (organization_id);

create index if not exists landing_page_templates_status_idx
on public.landing_page_templates (status);

create unique index if not exists landing_page_templates_org_slug_idx
on public.landing_page_templates (organization_id, slug)
where slug is not null;
