-- ============================================================================
-- Migration: Create task_templates table
-- Blueprint definitions for tasks that can be auto-created when a deal
-- enters a specific stage. Org-scoped.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.task_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  deal_stage_id bigint,
  code text NOT NULL,
  name text NOT NULL,
  description text,
  default_status_id bigint,
  default_priority_id bigint,
  due_offset_days integer,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT task_templates_uuid_key UNIQUE (uuid),
  CONSTRAINT task_templates_org_code_key UNIQUE (organization_id, code),
  CONSTRAINT task_templates_organization_id_fkey
    FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT task_templates_deal_stage_id_fkey
    FOREIGN KEY (deal_stage_id) REFERENCES public.deal_stages(id),
  CONSTRAINT task_templates_default_status_id_fkey
    FOREIGN KEY (default_status_id) REFERENCES public.task_statuses(id),
  CONSTRAINT task_templates_default_priority_id_fkey
    FOREIGN KEY (default_priority_id) REFERENCES public.task_priorities(id)
);

-- RLS
ALTER TABLE public.task_templates ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.task_templates TO authenticated;
GRANT ALL ON public.task_templates TO service_role;
CREATE POLICY "task_templates_select_authenticated"
  ON public.task_templates FOR SELECT TO authenticated USING (true);

-- Auto-update updated_at
CREATE OR REPLACE TRIGGER task_templates_updated_at
  BEFORE UPDATE ON public.task_templates
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();
