-- =====================================================
-- Migration: Alter inputs table + Create document_files_inputs
-- Date: 2026-02-12
--
-- Changes:
--   1. Rename inputs.id → inputs.input_code
--   2. Add inputs.input_id (UUID, UNIQUE)
--   3. Create document_files_inputs junction table
-- =====================================================

BEGIN;

-- =====================================================
-- STEP 1: Rename inputs.id → inputs.input_code
-- =====================================================
ALTER TABLE public.inputs
  RENAME COLUMN id TO input_code;

-- =====================================================
-- STEP 2: Add input_id UUID column with UNIQUE constraint
-- =====================================================
ALTER TABLE public.inputs
  ADD COLUMN input_id uuid NOT NULL DEFAULT gen_random_uuid();

ALTER TABLE public.inputs
  ADD CONSTRAINT inputs_input_id_key UNIQUE (input_id);

-- =====================================================
-- STEP 3: Create document_files_inputs linking table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.document_files_inputs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  document_file_id bigint NOT NULL,
  input_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by text NULL,
  CONSTRAINT document_files_inputs_pkey PRIMARY KEY (id),
  CONSTRAINT document_files_inputs_document_file_id_input_id_key
    UNIQUE (document_file_id, input_id),
  CONSTRAINT document_files_inputs_document_file_id_fkey
    FOREIGN KEY (document_file_id) REFERENCES document_files(id) ON DELETE CASCADE,
  CONSTRAINT document_files_inputs_input_id_fkey
    FOREIGN KEY (input_id) REFERENCES inputs(input_id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_document_files_inputs_doc
  ON public.document_files_inputs USING btree (document_file_id)
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_document_files_inputs_input
  ON public.document_files_inputs USING btree (input_id)
  TABLESPACE pg_default;

-- =====================================================
-- Verification
-- =====================================================
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'inputs' AND table_schema = 'public'
ORDER BY ordinal_position;

SELECT tablename FROM pg_tables
WHERE schemaname = 'public' AND tablename = 'document_files_inputs';

COMMIT;
