BEGIN;

-- 1) Org-aware document status lookup table (temporary plural name).
-- This will be renamed to document_status after enum removal.
CREATE TABLE IF NOT EXISTS public.document_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  code text NOT NULL,
  label text NOT NULL,
  color text NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  is_terminal boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Global uniqueness (organization_id IS NULL).
CREATE UNIQUE INDEX IF NOT EXISTS document_statuses_code_global_uniq
  ON public.document_statuses (code)
  WHERE organization_id IS NULL;

-- Per-org uniqueness (organization_id IS NOT NULL).
CREATE UNIQUE INDEX IF NOT EXISTS document_statuses_code_org_uniq
  ON public.document_statuses (organization_id, code)
  WHERE organization_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS document_statuses_org_display_idx
  ON public.document_statuses (organization_id, display_order, label);

-- 2) Per-org status assignment table.
CREATE TABLE IF NOT EXISTS public.document_file_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_file_id bigint NOT NULL
    REFERENCES public.document_files(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL
    REFERENCES public.organizations(id) ON DELETE CASCADE,
  document_status_id bigint NOT NULL
    REFERENCES public.document_statuses(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint NULL REFERENCES public.users(id) ON DELETE SET NULL,
  updated_by bigint NULL REFERENCES public.users(id) ON DELETE SET NULL,
  note text NULL,
  CONSTRAINT document_file_statuses_doc_org_uniq
    UNIQUE (document_file_id, organization_id)
);

CREATE INDEX IF NOT EXISTS document_file_statuses_org_status_idx
  ON public.document_file_statuses (organization_id, document_status_id);

CREATE INDEX IF NOT EXISTS document_file_statuses_doc_idx
  ON public.document_file_statuses (document_file_id);

-- 3) Assignment validation trigger.
CREATE OR REPLACE FUNCTION public.validate_document_file_status_assignment()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_status_org_id uuid;
  v_status_is_active boolean;
BEGIN
  SELECT ds.organization_id, ds.is_active
    INTO v_status_org_id, v_status_is_active
  FROM public.document_statuses ds
  WHERE ds.id = NEW.document_status_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid document_status_id: %', NEW.document_status_id;
  END IF;

  IF v_status_is_active IS NOT TRUE THEN
    RAISE EXCEPTION 'Cannot assign inactive status id=%', NEW.document_status_id;
  END IF;

  IF v_status_org_id IS NOT NULL AND v_status_org_id <> NEW.organization_id THEN
    RAISE EXCEPTION
      'Status org mismatch. status.organization_id=% assignment.organization_id=%',
      v_status_org_id, NEW.organization_id;
  END IF;

  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_document_file_status_assignment
  ON public.document_file_statuses;

CREATE TRIGGER trg_validate_document_file_status_assignment
BEFORE INSERT OR UPDATE ON public.document_file_statuses
FOR EACH ROW
EXECUTE FUNCTION public.validate_document_file_status_assignment();

COMMIT;
