-- ============================================================================
-- Migration: Create deal_task_events audit log table
-- Tracks task state changes for audit/history purposes.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.deal_task_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_task_id bigint NOT NULL,
  event_type text NOT NULL,
  old_value text,
  new_value text,
  performed_by text,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT deal_task_events_deal_task_id_fkey
    FOREIGN KEY (deal_task_id) REFERENCES public.deal_tasks(id) ON DELETE CASCADE
);

-- FK index
CREATE INDEX IF NOT EXISTS deal_task_events_deal_task_id_idx
  ON public.deal_task_events(deal_task_id);

-- RLS
ALTER TABLE public.deal_task_events ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.deal_task_events TO authenticated;
GRANT ALL ON public.deal_task_events TO service_role;
CREATE POLICY "deal_task_events_select_authenticated"
  ON public.deal_task_events FOR SELECT TO authenticated USING (true);
