-- =====================================================
-- Migration: Create Document Workflow Tables
-- Date: 2026-02-12
-- Description: Tracks 9 tables created directly in remote DB by Chris Lesnik.
--   These support document types, logic rules, AI conditions,
--   deal-level document overrides, and deal document uploads.
-- Dependencies: document_categories, deals, inputs
-- =====================================================

BEGIN;

-- =====================================================
-- 1. document_types
--    Defines the types of documents within each category
-- =====================================================
CREATE TABLE IF NOT EXISTS public.document_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_category_id bigint REFERENCES public.document_categories(id) ON DELETE SET NULL,
  document_name text,
  document_description text,
  display_order integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.document_types IS 'Types of documents within each category (e.g., Bank Statements, Tax Returns)';

-- =====================================================
-- 2. deal_documents
--    Files uploaded against a deal, optionally typed
-- =====================================================
CREATE TABLE IF NOT EXISTS public.deal_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id uuid NOT NULL REFERENCES public.deals(id) ON DELETE CASCADE,
  document_type_id bigint REFERENCES public.document_types(id) ON DELETE SET NULL,
  file_name text NOT NULL,
  file_size bigint,
  file_type text,
  storage_path text,
  uploaded_by text,
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deal_documents_deal_id ON public.deal_documents(deal_id);
CREATE INDEX IF NOT EXISTS idx_deal_documents_document_type_id ON public.deal_documents(document_type_id);

COMMENT ON TABLE public.deal_documents IS 'Files uploaded to a deal, linked to document types';

-- =====================================================
-- 3. deal_document_overrides
--    Per-deal overrides for document type visibility/required
-- =====================================================
CREATE TABLE IF NOT EXISTS public.deal_document_overrides (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id uuid NOT NULL REFERENCES public.deals(id) ON DELETE CASCADE,
  document_type_id bigint NOT NULL REFERENCES public.document_types(id) ON DELETE CASCADE,
  is_visible_override boolean,
  is_required_override boolean,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (deal_id, document_type_id)
);

CREATE INDEX IF NOT EXISTS idx_deal_document_overrides_deal_id ON public.deal_document_overrides(deal_id);

COMMENT ON TABLE public.deal_document_overrides IS 'Per-deal overrides for document type visibility and required status';

-- =====================================================
-- 4. document_logic
--    Top-level logic rule container
-- =====================================================
CREATE TABLE IF NOT EXISTS public.document_logic (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.document_logic IS 'Container for document logic rules (conditions + actions)';

-- =====================================================
-- 5. document_logic_conditions
--    Conditions that evaluate inputs to trigger actions
-- =====================================================
CREATE TABLE IF NOT EXISTS public.document_logic_conditions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_logic_id bigint REFERENCES public.document_logic(id) ON DELETE CASCADE,
  field uuid REFERENCES public.inputs(id) ON DELETE SET NULL,
  operator text,
  value text,
  value_type text DEFAULT 'value',
  value_expression text,
  value_field uuid REFERENCES public.inputs(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_document_logic_conditions_logic_id ON public.document_logic_conditions(document_logic_id);

COMMENT ON TABLE public.document_logic_conditions IS 'Conditions within a logic rule that reference input fields';

-- =====================================================
-- 6. document_logic_actions
--    Actions that fire when logic conditions are met
-- =====================================================
CREATE TABLE IF NOT EXISTS public.document_logic_actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_logic_id bigint REFERENCES public.document_logic(id) ON DELETE CASCADE,
  document_type_id bigint REFERENCES public.document_types(id) ON DELETE SET NULL,
  value_type text,
  value_visible boolean,
  value_required boolean,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_document_logic_actions_logic_id ON public.document_logic_actions(document_logic_id);

COMMENT ON TABLE public.document_logic_actions IS 'Actions that set document type visibility/required when conditions are met';

-- =====================================================
-- 7. document_type_ai_condition
--    AI-powered conditions tied to a document type
-- =====================================================
CREATE TABLE IF NOT EXISTS public.document_type_ai_condition (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type bigint REFERENCES public.document_types(id) ON DELETE CASCADE,
  condition_label text,
  ai_prompt text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_document_type_ai_condition_doc_type ON public.document_type_ai_condition(document_type);

COMMENT ON TABLE public.document_type_ai_condition IS 'AI conditions for document types — prompts that evaluate uploaded docs';

-- =====================================================
-- 8. document_type_ai_input
--    AI extraction targets: map document types to inputs
-- =====================================================
CREATE TABLE IF NOT EXISTS public.document_type_ai_input (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type_id bigint REFERENCES public.document_types(id) ON DELETE CASCADE,
  input_id uuid REFERENCES public.inputs(id) ON DELETE SET NULL,
  ai_prompt text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_document_type_ai_input_doc_type ON public.document_type_ai_input(document_type_id);

COMMENT ON TABLE public.document_type_ai_input IS 'Maps document types to inputs for AI data extraction';

-- =====================================================
-- 9. document_type_ai_input_order
--    Display ordering for AI input mappings
-- =====================================================
CREATE TABLE IF NOT EXISTS public.document_type_ai_input_order (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type_ai_input_id bigint REFERENCES public.document_type_ai_input(id) ON DELETE CASCADE,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.document_type_ai_input_order IS 'Display ordering for document type AI input mappings';

-- =====================================================
-- Enable RLS on all new tables (policies to be added separately)
-- =====================================================
ALTER TABLE public.document_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deal_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deal_document_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_logic ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_logic_conditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_logic_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_type_ai_condition ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_type_ai_input ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_type_ai_input_order ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- Grant service_role full access (for API routes)
-- =====================================================
GRANT ALL ON public.document_types TO service_role;
GRANT ALL ON public.deal_documents TO service_role;
GRANT ALL ON public.deal_document_overrides TO service_role;
GRANT ALL ON public.document_logic TO service_role;
GRANT ALL ON public.document_logic_conditions TO service_role;
GRANT ALL ON public.document_logic_actions TO service_role;
GRANT ALL ON public.document_type_ai_condition TO service_role;
GRANT ALL ON public.document_type_ai_input TO service_role;
GRANT ALL ON public.document_type_ai_input_order TO service_role;

-- Grant authenticated users read access on lookup tables
GRANT SELECT ON public.document_types TO authenticated;
GRANT SELECT ON public.document_logic TO authenticated;
GRANT SELECT ON public.document_logic_conditions TO authenticated;
GRANT SELECT ON public.document_logic_actions TO authenticated;
GRANT SELECT ON public.document_type_ai_condition TO authenticated;
GRANT SELECT ON public.document_type_ai_input TO authenticated;
GRANT SELECT ON public.document_type_ai_input_order TO authenticated;

-- Deal-scoped tables: authenticated users need CRUD via RLS
GRANT ALL ON public.deal_documents TO authenticated;
GRANT ALL ON public.deal_document_overrides TO authenticated;

-- Grant sequence usage
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO service_role;

COMMIT;
