BEGIN;

-- ============================================================================
-- 1. Alter appraisal table - add missing columns
-- ============================================================================
ALTER TABLE public.appraisal
  ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id),
  ADD COLUMN IF NOT EXISTS borrower_id uuid REFERENCES public.borrowers(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS borrower_name text,
  ADD COLUMN IF NOT EXISTS loan_number text,
  ADD COLUMN IF NOT EXISTS property_address text,
  ADD COLUMN IF NOT EXISTS property_city text,
  ADD COLUMN IF NOT EXISTS property_state text,
  ADD COLUMN IF NOT EXISTS property_zip text,
  ADD COLUMN IF NOT EXISTS amc_id bigint,
  ADD COLUMN IF NOT EXISTS date_due date,
  ADD COLUMN IF NOT EXISTS created_by text;

CREATE INDEX IF NOT EXISTS idx_appraisal_org ON public.appraisal(organization_id);
CREATE INDEX IF NOT EXISTS idx_appraisal_deal ON public.appraisal(deal_id);
CREATE INDEX IF NOT EXISTS idx_appraisal_borrower ON public.appraisal(borrower_id);

-- RLS
ALTER TABLE public.appraisal ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.appraisal TO authenticated;
GRANT ALL ON public.appraisal TO service_role;

CREATE POLICY "appraisal_select" ON public.appraisal
  FOR SELECT TO authenticated
  USING (organization_id = get_active_org_id());

CREATE POLICY "appraisal_insert" ON public.appraisal
  FOR INSERT TO authenticated
  WITH CHECK (organization_id = get_active_org_id());

CREATE POLICY "appraisal_update" ON public.appraisal
  FOR UPDATE TO authenticated
  USING (organization_id = get_active_org_id());

CREATE POLICY "appraisal_delete" ON public.appraisal
  FOR DELETE TO authenticated
  USING (organization_id = get_active_org_id());

-- ============================================================================
-- 2. Create appraisal_amcs lookup table
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.appraisal_amcs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id),
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_appraisal_amcs_org ON public.appraisal_amcs(organization_id);

COMMENT ON TABLE public.appraisal_amcs IS 'Lookup table for Appraisal Management Companies per org';

ALTER TABLE public.appraisal_amcs ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.appraisal_amcs TO authenticated;
GRANT ALL ON public.appraisal_amcs TO service_role;

CREATE POLICY "appraisal_amcs_select" ON public.appraisal_amcs
  FOR SELECT TO authenticated
  USING (organization_id = get_active_org_id());

CREATE POLICY "appraisal_amcs_insert" ON public.appraisal_amcs
  FOR INSERT TO authenticated
  WITH CHECK (organization_id = get_active_org_id());

CREATE POLICY "appraisal_amcs_update" ON public.appraisal_amcs
  FOR UPDATE TO authenticated
  USING (organization_id = get_active_org_id());

CREATE POLICY "appraisal_amcs_delete" ON public.appraisal_amcs
  FOR DELETE TO authenticated
  USING (organization_id = get_active_org_id());

-- ============================================================================
-- 3. FK from appraisal.amc_id to appraisal_amcs.id
-- ============================================================================
ALTER TABLE public.appraisal
  ADD CONSTRAINT appraisal_amc_id_fkey
  FOREIGN KEY (amc_id) REFERENCES public.appraisal_amcs(id) ON DELETE SET NULL;

COMMIT;
