-- ============================================================================
-- Migration: Create deal_tasks table
-- Per-deal task instances. Can be created from a template (auto) or ad-hoc.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.deal_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL,
  organization_id uuid,
  task_template_id bigint,
  title text NOT NULL,
  description text,
  task_status_id bigint,
  task_priority_id bigint,
  assigned_to_user_ids jsonb DEFAULT '[]'::jsonb,
  due_date_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  display_order integer DEFAULT 0,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT deal_tasks_uuid_key UNIQUE (uuid),
  CONSTRAINT deal_tasks_deal_id_fkey
    FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE CASCADE,
  CONSTRAINT deal_tasks_organization_id_fkey
    FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT deal_tasks_task_template_id_fkey
    FOREIGN KEY (task_template_id) REFERENCES public.task_templates(id) ON DELETE SET NULL,
  CONSTRAINT deal_tasks_task_status_id_fkey
    FOREIGN KEY (task_status_id) REFERENCES public.task_statuses(id),
  CONSTRAINT deal_tasks_task_priority_id_fkey
    FOREIGN KEY (task_priority_id) REFERENCES public.task_priorities(id)
);

-- FK indexes for common query patterns
CREATE INDEX IF NOT EXISTS deal_tasks_deal_id_idx
  ON public.deal_tasks(deal_id);
CREATE INDEX IF NOT EXISTS deal_tasks_task_status_id_idx
  ON public.deal_tasks(task_status_id);
CREATE INDEX IF NOT EXISTS deal_tasks_organization_id_idx
  ON public.deal_tasks(organization_id);

-- RLS
ALTER TABLE public.deal_tasks ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.deal_tasks TO authenticated;
GRANT ALL ON public.deal_tasks TO service_role;
CREATE POLICY "deal_tasks_select_authenticated"
  ON public.deal_tasks FOR SELECT TO authenticated USING (true);

-- Auto-update updated_at
CREATE OR REPLACE TRIGGER deal_tasks_updated_at
  BEFORE UPDATE ON public.deal_tasks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();
