-- ============================================================================
-- Migration: Create actions table
-- Stores workflow automation actions with their React Flow canvas data.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  workflow_data jsonb DEFAULT '{}',
  is_active boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT actions_uuid_key UNIQUE (uuid)
);

-- RLS
ALTER TABLE public.actions ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.actions TO authenticated;
GRANT ALL ON public.actions TO service_role;
CREATE POLICY "actions_select_authenticated"
  ON public.actions FOR SELECT TO authenticated USING (true);

-- Auto-update updated_at
CREATE OR REPLACE TRIGGER actions_updated_at
  BEFORE UPDATE ON public.actions
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();
