-- ============================================================================
-- Migration: Create task_logic, task_logic_conditions, task_logic_actions
-- Normalized 3-table rule engine (mirrors input_logic pattern).
-- ============================================================================

-- --------------------------------------------------------------------------
-- Table: task_logic (parent rule)
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.task_logic (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_template_id bigint NOT NULL,
  name text,
  description text,
  type text NOT NULL DEFAULT 'AND',
  is_active boolean DEFAULT true,
  execution_order integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT task_logic_task_template_id_fkey
    FOREIGN KEY (task_template_id) REFERENCES public.task_templates(id) ON DELETE CASCADE
);

-- FK index
CREATE INDEX IF NOT EXISTS task_logic_task_template_id_idx
  ON public.task_logic(task_template_id);

-- RLS
ALTER TABLE public.task_logic ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.task_logic TO authenticated;
GRANT ALL ON public.task_logic TO service_role;
CREATE POLICY "task_logic_select_authenticated"
  ON public.task_logic FOR SELECT TO authenticated USING (true);


-- --------------------------------------------------------------------------
-- Table: task_logic_conditions (child conditions)
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.task_logic_conditions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_logic_id bigint NOT NULL,
  field text,
  operator text,
  value text,
  value_type text DEFAULT 'value',
  value_field text,
  value_expression text,

  CONSTRAINT task_logic_conditions_task_logic_id_fkey
    FOREIGN KEY (task_logic_id) REFERENCES public.task_logic(id) ON DELETE CASCADE
);

-- FK index
CREATE INDEX IF NOT EXISTS task_logic_conditions_task_logic_id_idx
  ON public.task_logic_conditions(task_logic_id);

-- RLS
ALTER TABLE public.task_logic_conditions ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.task_logic_conditions TO authenticated;
GRANT ALL ON public.task_logic_conditions TO service_role;
CREATE POLICY "task_logic_conditions_select_authenticated"
  ON public.task_logic_conditions FOR SELECT TO authenticated USING (true);


-- --------------------------------------------------------------------------
-- Table: task_logic_actions (child actions)
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.task_logic_actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_logic_id bigint NOT NULL,
  action_type text NOT NULL,
  target_task_template_id bigint,
  value_type text DEFAULT 'value',
  value_text text,
  value_visible boolean,
  value_required boolean,
  value_field text,
  value_expression text,

  CONSTRAINT task_logic_actions_task_logic_id_fkey
    FOREIGN KEY (task_logic_id) REFERENCES public.task_logic(id) ON DELETE CASCADE,
  CONSTRAINT task_logic_actions_target_template_fkey
    FOREIGN KEY (target_task_template_id) REFERENCES public.task_templates(id) ON DELETE SET NULL
);

-- FK index
CREATE INDEX IF NOT EXISTS task_logic_actions_task_logic_id_idx
  ON public.task_logic_actions(task_logic_id);

-- RLS
ALTER TABLE public.task_logic_actions ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.task_logic_actions TO authenticated;
GRANT ALL ON public.task_logic_actions TO service_role;
CREATE POLICY "task_logic_actions_select_authenticated"
  ON public.task_logic_actions FOR SELECT TO authenticated USING (true);
