-- ============================================================
-- EMAIL TEMPLATES TABLE
-- For Liveblocks + Tiptap + compiled Gmail/Outlook output
-- ============================================================

create table if not exists public.email_templates (
  id bigint generated by default as identity primary key,

  -- Required tenancy
  organization_id uuid not null
    references public.organizations(id) on delete restrict,

  -- Human fields
  name text not null default 'Untitled Template',
  subject text not null default '',
  preview_text text not null default '',

  -- Sender configuration (validated at publish/send time)
  from_address text null,
  reply_to text null,

  -- Liveblocks room binding (recommend: template:{id})
  liveblocks_room_id text unique,

  -- Canonical editable content (Tiptap JSON)
  editor_json jsonb not null default
    jsonb_build_object(
      'type','doc',
      'content', jsonb_build_array(
        jsonb_build_object('type','paragraph')
      )
    ),

  -- Compiled outputs (email-safe HTML + plain text)
  email_output_html text null,
  email_output_text text null,

  -- Optional style metadata
  styles jsonb not null default '{}'::jsonb,

  -- Lifecycle
  status text not null default 'draft'
    check (status in ('draft', 'published')),
  published_at timestamptz null,

  schema_version int not null default 1,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- RLS (policies handled by your custom engine)
-- ============================================================

alter table public.email_templates enable row level security;

-- ============================================================
-- UPDATED_AT TRIGGER (reuse existing generic function)
-- ============================================================

drop trigger if exists email_templates_updated_at on public.email_templates;

create trigger email_templates_updated_at
before update on public.email_templates
for each row
execute function public.set_current_timestamp_updated_at();

-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists email_templates_organization_id_idx
on public.email_templates (organization_id);

create index if not exists email_templates_status_idx
on public.email_templates (status);
