-- ============================================================================
-- Migration: Create task_statuses and task_priorities lookup tables
-- ============================================================================

-- --------------------------------------------------------------------------
-- Table: task_statuses
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.task_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  color text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT task_statuses_uuid_key UNIQUE (uuid),
  CONSTRAINT task_statuses_code_key UNIQUE (code)
);

-- RLS
ALTER TABLE public.task_statuses ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.task_statuses TO authenticated;
GRANT ALL ON public.task_statuses TO service_role;
CREATE POLICY "task_statuses_select_authenticated"
  ON public.task_statuses FOR SELECT TO authenticated USING (true);

-- Auto-update updated_at
CREATE OR REPLACE TRIGGER task_statuses_updated_at
  BEFORE UPDATE ON public.task_statuses
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();

-- Seed data
INSERT INTO public.task_statuses (code, name, color, display_order) VALUES
  ('todo',        'To Do',        '#6B7280', 1),
  ('in_progress', 'In Progress',  '#3B82F6', 2),
  ('in_review',   'In Review',    '#F59E0B', 3),
  ('blocked',     'Blocked',      '#EF4444', 4),
  ('done',        'Done',         '#10B981', 5);


-- --------------------------------------------------------------------------
-- Table: task_priorities
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.task_priorities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  color text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT task_priorities_uuid_key UNIQUE (uuid),
  CONSTRAINT task_priorities_code_key UNIQUE (code)
);

-- RLS
ALTER TABLE public.task_priorities ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.task_priorities TO authenticated;
GRANT ALL ON public.task_priorities TO service_role;
CREATE POLICY "task_priorities_select_authenticated"
  ON public.task_priorities FOR SELECT TO authenticated USING (true);

-- Auto-update updated_at
CREATE OR REPLACE TRIGGER task_priorities_updated_at
  BEFORE UPDATE ON public.task_priorities
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();

-- Seed data
INSERT INTO public.task_priorities (code, name, color, display_order) VALUES
  ('low',    'Low',    '#6B7280', 1),
  ('medium', 'Medium', '#3B82F6', 2),
  ('high',   'High',   '#F59E0B', 3),
  ('urgent', 'Urgent', '#EF4444', 4);
