BEGIN;

-- ============================================================================
-- 1. credit_report_data_links - aggregator-agnostic junction table
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.credit_report_data_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  credit_report_id uuid NOT NULL REFERENCES public.credit_reports(id) ON DELETE CASCADE,
  aggregator text NOT NULL DEFAULT 'xactus',
  aggregator_data_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT credit_report_data_links_unique UNIQUE (credit_report_id, aggregator)
);

CREATE INDEX IF NOT EXISTS idx_crdl_credit_report ON public.credit_report_data_links(credit_report_id);
CREATE INDEX IF NOT EXISTS idx_crdl_aggregator_data ON public.credit_report_data_links(aggregator_data_id);

COMMENT ON TABLE public.credit_report_data_links IS 'Links credit_reports to aggregator-specific data tables (xactus, etc.)';

ALTER TABLE public.credit_report_data_links ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.credit_report_data_links TO authenticated;
GRANT ALL ON public.credit_report_data_links TO service_role;

CREATE POLICY "crdl_select" ON public.credit_report_data_links
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.credit_reports cr
    WHERE cr.id = credit_report_id
    AND cr.organization_id = get_active_org_id()
  ));

CREATE POLICY "crdl_insert" ON public.credit_report_data_links
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.credit_reports cr
    WHERE cr.id = credit_report_id
    AND cr.organization_id = get_active_org_id()
  ));

CREATE POLICY "crdl_delete" ON public.credit_report_data_links
  FOR DELETE TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.credit_reports cr
    WHERE cr.id = credit_report_id
    AND cr.organization_id = get_active_org_id()
  ));

-- ============================================================================
-- 2. Add organization_id to credit_report_data_xactus
-- ============================================================================
ALTER TABLE public.credit_report_data_xactus
  ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id);

COMMIT;
