-- =====================================================
-- Migration 3: Document Files
-- Date: 2026-01-28
-- Description: Create document metadata storage
-- Dependencies: Migration 2 (document_categories, document_status)
-- Breaking Changes: None
-- Risk Level: LOW
-- =====================================================

BEGIN;

-- =====================================================
-- Verify dependencies
-- =====================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_name = 'document_categories'
  ) THEN
    RAISE EXCEPTION 'Migration 3 failed: document_categories table not found. Run Migration 2 first.';
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_type 
    WHERE typname = 'document_status'
  ) THEN
    RAISE EXCEPTION 'Migration 3 failed: document_status enum not found. Run Migration 2 first.';
  END IF;
END $$;

-- =====================================================
-- Create document_files table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.document_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  public_notes text NULL,
  private_notes text NULL,
  effective_date date NULL,
  expiration_date date NULL,
  is_required boolean NULL,
  uploaded_by text NULL,
  uploaded_at timestamp with time zone NULL,
  file_size bigint NULL,
  file_type text NULL,
  document_name text NULL,
  document_status public.document_status NULL,
  storage_bucket text NULL,
  storage_path text NULL,
  tags text[] NULL DEFAULT ARRAY[]::text[],
  period_start date NULL,
  period_end date NULL,
  document_category_id bigint NULL,
  CONSTRAINT document_files_pkey PRIMARY KEY (id),
  CONSTRAINT document_files_storage_bucket_storage_path_key 
    UNIQUE (storage_bucket, storage_path),
  CONSTRAINT document_files_document_category_id_fkey 
    FOREIGN KEY (document_category_id) 
    REFERENCES document_categories(id) 
    ON DELETE SET NULL
) TABLESPACE pg_default;

-- =====================================================
-- Create indexes for performance
-- =====================================================
CREATE UNIQUE INDEX IF NOT EXISTS document_files_pkey 
  ON public.document_files USING btree (id) 
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_document_files_storage_location 
  ON public.document_files USING btree (storage_bucket, storage_path) 
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_document_files_tags 
  ON public.document_files USING gin (tags) 
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_document_files_period 
  ON public.document_files USING btree (period_start, period_end) 
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_document_files_bucket 
  ON public.document_files USING btree (storage_bucket) 
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_document_files_document_category_id 
  ON public.document_files USING btree (document_category_id) 
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_document_files_uploaded_by
  ON public.document_files USING btree (uploaded_by)
  TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_document_files_document_status
  ON public.document_files USING btree (document_status)
  TABLESPACE pg_default;

-- =====================================================
-- Enable RLS
-- =====================================================
ALTER TABLE public.document_files ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- Create basic RLS policies (placeholder - will be enhanced)
-- =====================================================
CREATE POLICY "Internal admins have full access to documents"
  ON public.document_files
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE clerk_user_id = auth.uid()::text 
        AND is_internal_yn = true
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE clerk_user_id = auth.uid()::text 
        AND is_internal_yn = true
    )
  );

-- Placeholder policy - will be replaced when helper functions are created
CREATE POLICY "Users can view their own documents (placeholder)"
  ON public.document_files
  FOR SELECT
  TO authenticated
  USING (uploaded_by = auth.uid()::text);

-- =====================================================
-- Verification
-- =====================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_name = 'document_files'
  ) THEN
    RAISE EXCEPTION 'Migration 3 failed: document_files table not created';
  END IF;
  
  -- Verify foreign key constraint exists
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'document_files'
      AND constraint_name = 'document_files_document_category_id_fkey'
  ) THEN
    RAISE EXCEPTION 'Migration 3 failed: foreign key constraint not created';
  END IF;
  
  RAISE NOTICE 'Migration 3 completed successfully';
END $$;

COMMIT;

-- =====================================================
-- Post-migration notes:
-- - document_files table created with all metadata columns
-- - Foreign key links to document_categories
-- - Indexes created for common query patterns (storage path, tags, dates)
-- - RLS enabled with basic policies
-- - Placeholder policy will be replaced in Migration 6 when helper functions exist
-- - Ready to store document metadata
-- =====================================================
