-- Create deal_stages table
CREATE TABLE IF NOT EXISTS public.deal_stages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  color text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT deal_stages_uuid_key UNIQUE (uuid),
  CONSTRAINT deal_stages_code_key UNIQUE (code)
);

-- Enable RLS
ALTER TABLE public.deal_stages ENABLE ROW LEVEL SECURITY;

-- Grant access to authenticated users (read-only for non-admins)
GRANT SELECT ON public.deal_stages TO authenticated;
GRANT ALL ON public.deal_stages TO service_role;

-- RLS: any authenticated user can read stages
CREATE POLICY "deal_stages_select_authenticated"
  ON public.deal_stages
  FOR SELECT
  TO authenticated
  USING (true);

-- Auto-update updated_at on row change
CREATE OR REPLACE TRIGGER deal_stages_updated_at
  BEFORE UPDATE ON public.deal_stages
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();
